workflows:
  my-workflow:
    scripts: 
      - name: multi-line script
        script: |

          echo first command
          curl "https://nodejs.org/dist/latest/node-${VERSION:-$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-(.*)\.pkg</a>.*|\1|p')}.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"
          echo node installed
          npm i -g @bubblewrap/cli
          echo bubblewrap installed
          cd $HOME
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install --cask android-sdk
          echo JDK installed
          bubblewrap doctor
          
