workflows:
  my-workflow:
    scripts: 
      - name: multi-line script
        script: |
          set -e # exit on first failed command

          echo first command
          echo second command
          npm i @bubblewrap/cli
          bubblewrap init --manifest=https://tikaoo.com/api/tikaoo.com/manifest.json

