workflows:
  my-workflow:
    scripts: 
      - name: multi-line script
        script: |

          echo first command
          curl "https://nodejs.org/dist/latest/node-${VERSION:-$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-(.*)\.pkg</a>.*|\1|p')}.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"
          echo node installed
          npm i -g @bubblewrap/cli
          echo bubblewrap installed
          cd $HOME
          sudo apt-get install libc6-dev-i386 lib32z1 openjdk-8-jdk
          echo JDK installed
          bubblewrap doctor
          
